# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-14 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20190414_1739'),
        ('lists', '0004_courses_list'),
    ]

    operations = [
    ]
